### ISSUE TITLE
Could not pass event PlayerInteractEvent to Kingdoms v1.11.13.1.1

### ISSUE THREAD

**Issue by Stormez1998** [CryptoMorin/KingdomsX#21]
Hay, me again.

i got that error:

`[15:12:36] [Server thread/ERROR] [Minecraft]: Could not pass event PlayerInteractEvent to Kingdoms v1.11.13.1.1
 org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:68) ~[EventExecutor.class:4152130-DEV]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[TimedEventExecutor.class:4152130-DEV]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:4152130-DEV]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:517) ~[SimplePluginManager.class:4152130-DEV]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:263) ~[CraftEventFactory.class:4152130-DEV]
	at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:479) ~[or.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:1141) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[ma.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[ma.class:?]
	at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:14) ~[hv.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_312]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_312]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:926) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:461) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:865) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:737) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
Caused by: java.lang.IllegalArgumentException: Unsupported material with no data value: FLANSMOD_FLANSWORKBENCH
	at org.kingdoms.utils.xseries.XMaterial.lambda$matchXMaterial$0(XMaterial.java:1664) ~[Kingdoms-1.11.13.1.1.jar:?]
	at java.util.Optional.orElseThrow(Optional.java:290) ~[?:1.8.0_312]
	at org.kingdoms.utils.xseries.XMaterial.matchXMaterial(XMaterial.java:1664) ~[Kingdoms-1.11.13.1.1.jar:?]
	at org.kingdoms.managers.land.InteractHandler.isInteractable(InteractHandler.java:26) ~[Kingdoms-1.11.13.1.1.jar:?]
	at org.kingdoms.managers.land.LandProtectionManager.onInteract(LandProtectionManager.java:542) ~[Kingdoms-1.11.13.1.1.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor446.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:66) ~[EventExecutor.class:4152130-DEV]`

**Comment by CryptoMorin** [comment]
Mods aren't supported.

**Comment by Stormez1998** [comment]
Can You tell me please what mod is the Problem?

**Comment by CryptoMorin** [comment]
Any mod that adds additional materials to the server isn't supported. I think this belongs to [Flan's Mod](https://ftbwiki.org/Flan%27s_Mod)
