### ISSUE TITLE
java.lang.NoSuchMethodError: 'java.lang.Boolean com.Zrips.CMI.Containers.CMIUser.isGod()

### ISSUE THREAD

**Issue by Ksewedo5** [CryptoMorin/KingdomsX#53]
[00:30:45 WARN]: [KingdomsX] Task #2360 for Kingdoms v1.16.4 generated an exception
java.lang.NoSuchMethodError: 'java.lang.Boolean com.Zrips.CMI.Containers.CMIUser.isGod()'
        at org.kingdoms.services.vanish.ServiceCMI.isInGodMode(ServiceCMI.java:17) ~[KingdomsX-1.16.4.jar:?]
        at org.kingdoms.services.managers.ServiceHandler.lambda$isInGodMode$2(ServiceHandler.java:114) ~[KingdomsX-1.16.4.jar:?]
        at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90) ~[?:?]
        at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:1002) ~[?:?]
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?]
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) ~[?:?]
        at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:632) ~[?:?]
        at org.kingdoms.services.managers.ServiceHandler.isInGodMode(ServiceHandler.java:114) ~[KingdomsX-1.16.4.jar:?]
        at org.kingdoms.managers.turrets.TurretTask.run(TurretTask.java:115) ~[KingdomsX-1.16.4.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.4.jar:git-Paper-514]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.4.jar:git-Paper-514]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1483) ~[paper-1.19.4.jar:git-Paper-514]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.19.4.jar:git-Paper-514]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.4.jar:git-Paper-514]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174) ~[paper-1.19.4.jar:git-Paper-514]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-514]
        at java.lang.Thread.run(Thread.java:833) ~[?:?

It's much better after the last update. But the error still occurs from time to time

Kingdoms - Latest
CMI - 9.5.0.7

**Comment by CryptoMorin** [comment]
Hi, please update to the latest version.
