### ISSUE TITLE
Hey. I got this error with my friend when we tried to do the /kingdom ally command

### ISSUE THREAD

**Issue by Keebsz** [CryptoMorin/KingdomsX#54]
I am on paper 1.19.3 Using KingdomsX 1.16.4

[05:21:14 WARN]: [KingdomsX] Plugin Kingdoms v1.16.4 generated an exception while executing task 298
java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "java.lang.invoke.MethodHandle.asType(java.lang.invoke.MethodType)" because "mh" is null
        at org.kingdoms.utils.nms.HologramFactory.spawn(HologramFactory.java:135) ~[KingdomsX-1.16.4.jar:?]
        at org.kingdoms.utils.nms.HologramFactory.spawn(HologramFactory.java:99) ~[KingdomsX-1.16.4.jar:?]
        at org.kingdoms.constants.land.abstraction.KingdomItem.spawnHolograms(KingdomItem.java:458) ~[KingdomsX-1.16.4.jar:?]
        at org.kingdoms.managers.land.holograms.KingdomItemHologramProcessor.process(KingdomItemHologramProcessor.java:69) ~[KingdomsX-1.16.4.jar:?]
        at org.kingdoms.managers.land.holograms.KingdomItemHologramManager.lambda$static$0(KingdomItemHologramManager.java:31) ~[KingdomsX-1.16.4.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.3.jar:git-Paper-448]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.3.jar:git-Paper-448]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.3.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.invoke.MethodHandle.asType(java.lang.invoke.MethodType)" because "mh" is null
        at java.lang.invoke.Invokers.checkGenericType(Invokers.java:542) ~[?:?]
        at org.kingdoms.utils.nms.HologramFactory.spawn(HologramFactory.java:122) ~[KingdomsX-1.16.4.jar:?]
        ... 10 more

**Comment by CryptoMorin** [comment]
The latest version only supports 1.19.4 from the 1.19 versions.

**Comment by CryptoMorin** [comment]
No worries.
