### ISSUE TITLE
claim-on-create - error 

### ISSUE THREAD

**Issue by Ksewedo5** [CryptoMorin/KingdomsX#56]
```
[23:50:09 INFO]: Lexxuss0PL issued server command: /k create test2
[23:50:09 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'k' in plugin Kingdoms v1.16.6.1
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[pufferfishplus-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[pufferfishplus-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.dispatchCommand() ~[pufferfishplus-1.19.4.jar:git-PufferfishPlusPurpur-19]
        at org.bukkit.craftbukkit.v1_19_R3.command.BukkitCommandWrapper.run() ~[pufferfishplus-1.19.4.jar:git-PufferfishPlusPurpur-19]
        at com.mojang.brigadier.CommandDispatcher.execute() ~[pufferfishplus-1.19.4.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java) ~[?:?]
        at net.minecraft.commands.Commands.a(Commands.java) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.a(ServerGamePacketListenerImpl.java) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$22(ServerGamePacketListenerImpl.java) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.b(BlockableEventLoop.java) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java) ~[pufferfishplus-1.19.4.jar:git-PufferfishPlusPurpur-19]
        at net.minecraft.util.thread.BlockableEventLoop.d(BlockableEventLoop.java) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.d(ReentrantBlockableEventLoop.java) ~[?:?]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java) ~[pufferfishplus-1.19.4.jar:git-PufferfishPlusPurpur-19]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java) ~[pufferfishplus-1.19.4.jar:git-PufferfishPlusPurpur-19]
        at net.minecraft.util.thread.BlockableEventLoop.x(BlockableEventLoop.java) ~[?:?]
        at net.minecraft.server.MinecraftServer.bi(MinecraftServer.java) ~[pufferfishplus-1.19.4.jar:git-PufferfishPlusPurpur-19]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java) ~[pufferfishplus-1.19.4.jar:git-PufferfishPlusPurpur-19]
        at net.minecraft.util.thread.BlockableEventLoop.c(BlockableEventLoop.java) ~[?:?]
        at net.minecraft.server.MinecraftServer.i_(MinecraftServer.java) ~[pufferfishplus-1.19.4.jar:git-PufferfishPlusPurpur-19]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java) ~[pufferfishplus-1.19.4.jar:git-PufferfishPlusPurpur-19]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java) ~[pufferfishplus-1.19.4.jar:git-PufferfishPlusPurpur-19]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Land 'Overworld, 11, 9' is already claimed by another kingdom: 4923dcfb-893c-4f81-98c2-bd16ad29ebce
        at org.kingdoms.events.lands.ClaimingEvent.cacheLands(ClaimingEvent.java:51) ~[KingdomsX-1.16.6.1.jar:?]
        at org.kingdoms.events.lands.ClaimingEvent.<init>(ClaimingEvent.java:36) ~[KingdomsX-1.16.6.1.jar:?]
        at org.kingdoms.events.lands.ClaimLandEvent.<init>(ClaimLandEvent.java:18) ~[KingdomsX-1.16.6.1.jar:?]
        at org.kingdoms.constants.group.Kingdom.claim(Kingdom.java:364) ~[KingdomsX-1.16.6.1.jar:?]
        at org.kingdoms.commands.general.misc.CommandCreate.execute(CommandCreate.java:125) ~[KingdomsX-1.16.6.1.jar:?]
        at org.kingdoms.commands.KingdomsCommandHandler.onCommand(KingdomsCommandHandler.java:306) ~[KingdomsX-1.16.6.1.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[pufferfishplus-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        ... 23 more
```

How to reproduce bug ? 

1.Open claims.yml set ,,claim-on-create" -> 4
1.Create 1 kingdoms -> Leave claim (1block) -> Create 2 kingdom

Translated by google

**Comment by CryptoMorin** [comment]
Fixed in v1.16.8

As a side note: this only happens when doing the command near another kingdom.
