### ISSUE TITLE
Why it automatically delete kingdom data

### ISSUE THREAD

**Issue by Leoparking** [CryptoMorin/KingdomsX#62]
一夜之间，所有数据都没有了
我们的王国全没了
你这插件安全性这么低，谁还玩
![CN RI_4 AJD L5E7}I5GKO6](https://github.com/CryptoMorin/KingdomsX/assets/141799770/a8a7bae3-f876-4867-bee0-3381ad64a391)

`[14:26:21] [Server thread/DEBUG] [com.mohistmc.MohistMC]: Transforming classloader class org/kingdoms/dependencies/classpath/IsolatedClassLoader
[14:26:22] [Server thread/ERROR] [Minecraft]: Error occurred while enabling Kingdoms v1.16.20.5 (Is it up to date?)
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.kingdoms.data.database.sql.SQLFlatFileConnectionProvider.<init>(SQLConnectionProvider.kt:110) ~[?:?]
	at org.kingdoms.data.database.sql.SQLConnectionProvider$Companion.getProvider(SQLConnectionProvider.kt:46) ~[?:?]
	at org.kingdoms.data.database.sql.SQLConnectionProvider.getProvider(SQLConnectionProvider.kt) ~[?:?]
	at org.kingdoms.data.KingdomsDataCenter.constructDatabase(KingdomsDataCenter.java:109) ~[?:?]
	at org.kingdoms.data.managers.NationManager.<init>(NationManager.java:20) ~[?:?]
	at org.kingdoms.data.KingdomsDataCenter.<init>(KingdomsDataCenter.java:38) ~[?:?]
	at org.kingdoms.main.Kingdoms.onEnable(Kingdoms.java:359) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:347) ~[forge-1.20.1-47.2.30-universal.jar%23241!/:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:336) ~[forge-1.20.1-47.2.30-universal.jar%23241!/:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:482) ~[forge-1.20.1-47.2.30-universal.jar%23241!/:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:550) ~[forge-1.20.1-47.2.30-universal.jar%23241!/:997de31d-ddc9a2dad-d2eba2c8-47.1.79]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:463) ~[forge-1.20.1-47.2.30-universal.jar%23241!/:997de31d-ddc9a2dad-d2eba2c8-47.1.79]
	at net.minecraft.server.MinecraftServer.m_129815_(MinecraftServer.java:441) ~[server-1.20.1-20230612.114412-srg.jar%23236!/:?]
	at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServer.java:341) ~[server-1.20.1-20230612.114412-srg.jar%23236!/:?]
	at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:224) ~[server-1.20.1-20230612.114412-srg.jar%23236!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:848) ~[server-1.20.1-20230612.114412-srg.jar%23236!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:281) ~[server-1.20.1-20230612.114412-srg.jar%23236!/:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(Unknown Source) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?]
	at org.kingdoms.data.database.sql.SQLFlatFileConnectionProvider.<init>(SQLConnectionProvider.kt:94) ~[?:?]
	... 17 more
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: File corrupted while reading record: "E:/地球村/plugins/Kingdoms/data/data.mv.db". Possible solution: use the recovery tool [90030-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:678) ~[?:?]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477) ~[?:?]
	at org.h2.message.DbException.get(DbException.java:212) ~[?:?]
	at org.h2.mvstore.db.Store.convertMVStoreException(Store.java:166) ~[?:?]
	at org.h2.mvstore.db.Store.<init>(Store.java:145) ~[?:?]
	at org.h2.engine.Database.<init>(Database.java:324) ~[?:?]
	at org.h2.engine.Engine.openSession(Engine.java:92) ~[?:?]
	at org.h2.engine.Engine.openSession(Engine.java:222) ~[?:?]
	at org.h2.engine.Engine.createSession(Engine.java:201) ~[?:?]
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338) ~[?:?]
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122) ~[?:?]
	at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(Unknown Source) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?]
	at org.kingdoms.data.database.sql.SQLFlatFileConnectionProvider.<init>(SQLConnectionProvider.kt:94) ~[?:?]
	... 17 more
Caused by: org.h2.mvstore.MVStoreException: File is corrupted - unable to recover a valid set of chunks [2.1.214/6]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:1004) ~[?:?]
	at org.h2.mvstore.MVStore.readStoreHeader(MVStore.java:1038) ~[?:?]
	at org.h2.mvstore.MVStore.<init>(MVStore.java:463) ~[?:?]
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:4082) ~[?:?]
	at org.h2.mvstore.db.Store.<init>(Store.java:136) ~[?:?]
	at org.h2.engine.Database.<init>(Database.java:324) ~[?:?]
	at org.h2.engine.Engine.openSession(Engine.java:92) ~[?:?]
	at org.h2.engine.Engine.openSession(Engine.java:222) ~[?:?]
	at org.h2.engine.Engine.createSession(Engine.java:201) ~[?:?]
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338) ~[?:?]
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122) ~[?:?]
	at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(Unknown Source) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?]
	at org.kingdoms.data.database.sql.SQLFlatFileConnectionProvider.<init>(SQLConnectionProvider.kt:94) ~[?:?]
	... 17 more
[14:26:22] [Server thread/INFO] [org.kingdoms.main.Kingdoms]: [KingdomsX] Disabling Kingdoms v1.16.20.5
[14:26:22] [Server thread/ERROR] [org.kingdoms.main.Kingdoms]: [KingdomsX] Plugin did not load properly to disable normally. Force disabling...`

**Comment by CryptoMorin** [comment]
I'm sorry for the late reply, but if you still need help you need to show me your full server logs.

**Comment by Leoparking** [comment]
> I'm sorry for the late reply, but if you still need help you need to show me your full server logs.

You did come late. It happened at the beginning of May. In the end, players had to start building again, and the server logs had already been cleared. The root cause is that the database is corrupted and several backup files are corrupted. It is recommended to enhance the security of the plugin

**Comment by CryptoMorin** [comment]
To prepare for future issues, read [this](https://github.com/CryptoMorin/KingdomsX/wiki/Troubleshooting#data-corruption).
